version: "3.7"
services:
  db:
    image: "postgres:latest"
    container_name: "Conversation-Prod-DB"
    restart: always
    environment:
      POSTGRES_USER: matheus_postgres
      POSTGRES_PASSWORD: matheus_postgres
      POSTGRES_DB: prodConversationDatabase
    ports:
      - "5432:5432"